// GET PRODUCT
export const GET_PRODUCT_PROGRESS = "GET_PRODUCT_PROGRESS";
export const GET_PRODUCT_SUCCESS = "GET_PRODUCT_SUCCESS";
export const GET_PRODUCT_ERROR = "GET_PRODUCT_ERROR";


// POST PRODUCT
export const POST_PRODUCT_PROGRESS = "POST_PRODUCT_PROGRESS";
export const POST_PRODUCT_SUCCESS = "POST_PRODUCT_SUCCESS";
export const POST_PRODUCT_ERROR = "POST_PRODUCT_ERROR";

// DELETE PRODUCT
export const DELETE_PRODUCT_PROGRESS = "DELETE_PRODUCT_PROGRESS";
export const DELETE_PRODUCT_SUCCESS = "DELETE_PRODUCT_SUCCESS";
export const DELETE_PRODUCT_ERROR = "DELETE_PRODUCT_ERROR";

// UPDATE
export const PATCH_PRODUCT_PROGRESS = "PATCH_PRODUCT_PROGRESS";
export const PATCH_PRODUCT_SUCCESS = "PATCH_PRODUCT_SUCCESS";
export const PATCH_PRODUCT_ERROR = "PATCH_PRODUCT_ERROR";